persowebpage/models.py
# # models.py
# from puppycompanyblog import db, login_manager # from __init__.py
# from werkzeug.security import generate_password_hash, check_password_hash
# from flask_login import UserMixin
# from datetime import datetime
#
# @login_manager.user_loader
# def load_user(user_id):
#     return User.query.get(user_id)
#
# class User(db.Model, UserMixin):
#
#     __tablename__ = 'users'
#
#     id = db.Column(db.Integer, primary_key=True)
#     profile_image = db.Column(db.String(64), nullable = False, default='default_profile.png')
#     email = db.Column(db.String(64), unique=True, index=True)
#     username = db.Column(db.String(64), unique=True, index=True)
#     password_hash = db.Column(db.String(128))
#
#     posts = db.relationship('BlogPost', backref='author', lazy=True) #author a a blog post is a user
#
#     def __init__(self, email, username, password):
#         self.email = email
#         self.username = username
#         self.password_hash = generate_password_hash(password)
# 
#     def check_password(self, password):
#         return check_password_hash(self.password_hash, password)
#
#     def __repr__(self):
#         return f'Username: {self.username}'
#
#
# class BlogPost(db.Model):
#     # users = db.relationship(User)
#
#     id = db.Column(db.Integer, primary_key=True)
#     user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable = False) # come to table names users and id attribute
#     date = db.Column(db.Date, nullable=False, default=datetime.utcnow)
#     title = db.Column(db.String(140), nullable=False)
#     test = db.Column(db.Text, nullable=False)
#
#     def __init__(self, title, text, user_id):
#         self.title = title
#         self.text = text
#         self.user_id = user_id
#
#     def __repr__(self):
#         return f'post ID: {self.id} -- Date: {self.date}'

persowebpage/__init__.py
# puppycompanyblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import os
from flask_login import LoginManager

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecret'

#####################################################
# db
# basedir = os.path.abspath(os.path.dirname(__file__))
#
# app.config['SQLALCHEMY_DATABASE_URI']  = 'sqlite:///'+os.path.join(basedir, 'data.sqlite')
# app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
#
# db = SQLAlchemy(app)
# Migrate(app, db)

#####################################################
# LoginManager

# login_manager = LoginManager()
#
# login_manager.init_app(app)
# login_manager.login_view  = 'users.login'

#####################################################

from persowebpage.contact.views import contact
from persowebpage.core.views import core
from persowebpage.error_pages.handlers import error_pages
from persowebpage.method.views import method
from persowebpage.publication.views import publication
from persowebpage.research.views import research
from persowebpage.teaching.views import teaching
from persowebpage.vitae.views import vitae

app.register_blueprint(contact)
app.register_blueprint(core)
app.register_blueprint(error_pages)
app.register_blueprint(method)
app.register_blueprint(publication)
app.register_blueprint(research)
app.register_blueprint(teaching)
app.register_blueprint(vitae)

persowebpage/contact/views.py
# Core / views.py
from flask import render_template, request, Blueprint

contact = Blueprint('contact', __name__)

@contact.route('/contact')
def cont():
    return render_template("contact.html")

persowebpage/core/views.py
# Core / views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    return render_template('index.html')

@core.route('/research')
def research():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('research.html')

@core.route('/License')
def license():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('license.html')

persowebpage/method/views.py
# Core / views.py
from flask import render_template, request, Blueprint

method = Blueprint('method', __name__)

@method.route('/method')
def methods():
    return render_template('method.html')

@method.route('/method/sampling_cambium')
def cambium():
    return render_template('cambium.html')

@method.route('/method/sandblasting_seeds')
def sandblasting():
    return render_template('sandblasting.html')

persowebpage/publication/views.py
# Core / views.py
from flask import render_template, request, Blueprint

publication = Blueprint('publication', __name__)

@publication.route('/publication')
def publi():
    return render_template("publication.html")

persowebpage/research/views.py
# Core / views.py
from flask import render_template, request, Blueprint

research = Blueprint('research', __name__)


@research.route('/research')
def researchs():
    return render_template("research.html")

@research.route('/research/invasive_species')
def invasive():
    return render_template("invasive.html")

@research.route('/research/drought_resitance')
def drought():
    return render_template("drought.html")

persowebpage/teaching/views.py
# Core / views.py
from flask import render_template, request, Blueprint

teaching = Blueprint('teaching', __name__)


@teaching.route('/teaching')
def teachings():
    return render_template("teaching.html")

@teaching.route('/teaching/Programming')
def programming():
    return render_template("programming.html")

@teaching.route('/teaching/statistics')
def stat():
    return render_template("statistics.html")

persowebpage/vitae/views.py
# Core / views.py
from flask import render_template, request, Blueprint

vitae = Blueprint('vitae', __name__)

@vitae.route('/vitae')
def cv():
    return render_template("vitae.html")

persowebpage/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>

  </head>
  <body>

    <ul class = 'nav'>
      <li class ='nav-link'>
        <a href="{{url_for('core.index')}}"> Home </a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{{url_for('research.researchs')}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Research
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Drought Resistance</a>
          <a class="dropdown-item" href="{{url_for('research.invasive')}}">Invasive Species: <span class="font-italic">Robinia pseudoacacia</span></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Personal Projects</a>
        </div>
      </li>

      <li class ='nav-link'>
        <a href="{{url_for('publication.publi')}}"> Publications </a>
      </li>

      <li class ='nav-link'>
        <a href="{{url_for('vitae.cv')}}"> Vitae </a>
      </li>

      <li class ='nav-link'>
        <a href="{{url_for('teaching.teachings')}}"> Teaching </a>
      </li>

      <li class ='nav-link'>
        <a href="{{url_for('contact.cont')}}"> Contact </a>
      </li>


      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{{url_for('method.methods')}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Methods
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{url_for('method.cambium')}}">Sampling Cambium</a>
          <a class="dropdown-item" href="{{url_for('method.sandblasting')}}">Sandblasting seeds</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="https://github.com/xbouteiller">Github</a>
        </div>
      </li> -->
    </ul>

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>


<div class="container">
  <footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright Xavier Bouteiller:
    <a href="{{url_for('core.license')}}">Terms and Conditions of Use</a>
  </div>
  <!-- Copyright -->

  </footer>
</div>

  </body>
</html>

persowebpage/templates/cambium.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> cambium
   </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> Contact </h1>
</div>

<div class="bd-example">
  <address>
    <strong>UMR BIOGECO, University of Bordeaux</strong><br/>
    Bat B2, Allée Geoffroy St-Hilaire<br/>
    33615 Pessac, France<b/>
    <!-- <abbr title="Phone">P:</abbr> (123) 456-7890 -->
  </address>

  <address>
    <strong>Dr Xavier Bouteiller</strong><br />
    <a href="mailto:bouteiller.xavier@gmail.com">bouteiller(dot)xavier(at)gmail(dot)com</a>
  </address>
</div>

{% endblock %}

persowebpage/templates/drought.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> Drought </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/index.html
{% extends "base.html" %}
{% block content %}

  <div class="jumbotron jumbotron-fluid">

    <h1> Welcome to Xavier Bouteiller's Home Page</h1>
    <br>
    <br>
    
    <blockquote class="blockquote">
      <p class="mb-0"> Il est démontré, disait-­il, que les choses ne peuvent être autrement : car tout étant fait pour une fin, tout est nécessairement pour la meilleure fin. Remarquez bien que les nez ont été faits pour porter des lunettes ; aussi avons ­nous des lunettes. Les jambes sont visiblement instituées pour être chaussées, et nous avons des chausses. [...]. Par conséquent, ceux qui ont avancé que tout est bien ont dit une sottise : il fallait dire que tout est au mieux.</p>
      <footer class="blockquote-footer">Voltaire <cite title="Source Title">Candide ou l’Optimisme, 1759</cite></footer>
    </blockquote>

  </div>



  <div class="container-fluid">

    <div class="card-deck">
      <div class="card border-0" style="width: 18rem;" align='center'>
        <img src="../static/XB.jpg" class="card-img-top img-thumbnail border-0" alt="...">
        <div class="card-body">
          <p class="card-text">Sampling Robinia throught America</p>
        </div>
      </div>
      <div class="card border-0">
        <div class="card-body">
          <p class="card-text text-justify">After studying Physics at the University, I started my career as a physics and chemistry teacher
within French secondary school. I went back to the University to study Biology and Ecology with the objective to
defend a PhD and pursue my career as a research scientist.</p>

<p class="card-text text-justify"> During
my PhD I focused on biological invasions. Thus my research concentrated on the role of evolutionary processes involved in the success of
the invasive tree species black locust (Robinia pseudoacacia L.). I used a combined approach
of population genetics and quantitative genetics to reconstruct the history of introduction from America to Europe of black locust and to detect any phenotypic differentiation on juvenile
traits among opulations</p>

<p class="card-text text-justify">I always have been very enthusiastic about teaching, thus I was involved in teaching statistics and programming with R for undergraduate and postgraduate students at Bordeaux University. I give also statistics and programming lectures to the Data Analyst and Data Scientist students at the private institute Bordeaux Data University</p>

<p class="card-text text-justify"> Recently I started also a Data Scientist career working for private companies. I focused on solving data related problem of my industrial clients as Ariane Group and Lectra. My main tasks were to collect and to analyze data with robust statistical models and to develop predictive models for anomaly detection.</p>
        </div>
      </div>
    </div>

  </div>

{% endblock %}

persowebpage/templates/invasive.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <h1>Invasive Species: <span class="font-italic">Robinia pseudoacacia</span>  </h1>
  <br>
</div>

<div class="container"">

 <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
 <br>

  <div class="card mb-3 border-0" >
    <div class="row no-gutters border-0">
      <div class="col-md-4  border-0" style="max-width: 200px;">
        <img src="../static/invasive/acp.jpg" class="card-img" alt="..." >
      </div>
      <div class="col-md-8 border-0">
        <div class="card-body  border-0">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
<br>

  <div class="card mb-3  border-0">
    <div class="row no-gutters border-0">
      <div class="col-md-4 border-0" style="max-width: 200px;">
        <img src="../static/invasive/us_surf.jpg" class="card-img" alt="...">
      </div>
      <div class="col-md-8 border-0">
        <div class="card-body  border-0">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
<br>

  <div class="card mb-3 border-0">
    <div class="row no-gutters border-0">
      <div class="col-md-4 border-0" style="max-width: 200px;">
        <img src="../static/invasive/germ_be_fr.jpg" class="card-img" alt="...">
      </div>
      <div class="col-md-8 border-0">
        <div class="card-body border-0">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>

</div>






{% endblock %}

persowebpage/templates/license.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> Terms and Conditions of Use </h1>



  <br>
</div>

  <p> This site was created by Xavier Bouteiller with Flask and Python, please contact the author at : bouteiller(dot)xavier(at)gmail(dot)com if you have anyy question or remark</p>


{% endblock %}

persowebpage/templates/method.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> method </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/programming.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> programming </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/publication.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> List of publications </h1>
  <br>
  <p> Please find below my list of publications</p>
</div>


<div class="Container">

  <h2> Papers </h2>
  <br>
  <h3>Submitted</h3>
  <ul class="list-group">
    <li class="list-group-item border-0"> Bouteiller et al. (submitted to biological invasions). The seeds of invasion: Enhanced germination among invasive European populations of black locust compared to native American populations </li>
    <li class="list-group-item border-0">Caignard, Kremer, Bouteiller et al. (submitted to New Phytol). Counter-gradient variation in reproductive effort of a broadly distributed temperate oak (Quercus petraea).</li>
  </ul>
  <br>
  <h3>Published</h3>
  <ul class="list-group">
    <li class="list-group-item border-0"> Bouteiller et al. (2019). A few North Appalachian populations are the source of European black locust. Ecol. Evol. 1-17. </li>
    <li class="list-group-item border-0">Bouteiller et al. (2018) No evidence for genetic differentiation in juvenile traits between Belgian and French populations of the invasive tree Robinia pseudoacacia. Plant Ecol Evol. 151(1), 5-17.</li>
    <li class="list-group-item border-0">Bouteiller et al. (2017) Using automated sanding to homogeneously break seed dormancy in black locust (Robinia pseudoacacia L., Fabaceae). Seed Sci Res. 27(3), 243-250.</li>
  </ul>
  <br>
  <br>
  <h2> Books </h2>
  <br>
  <ul class="list-group">
    <li class="list-group-item border-0"> Nogues X, Garenne A, Bouteiller XP and Fievet V. Biostatistique, Le cours. Livre Collection : Tout en fiches. Dunod, Paris. 384p. 2018. </li>
    <li class="list-group-item border-0">Bouteiller XP. A European ecological and evolutionary history of black locust (Robinia pseudoacacia L.). Doctoral dissertation. University of Bordeaux. 255p. 2018</li>
  </ul>

</div>


{% endblock %}

persowebpage/templates/research.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> research </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/sandblasting.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
  <h1> sandblasting </h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

persowebpage/templates/teaching.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
  <h1>Teaching </h1>
  <br>
  <br>
  <blockquote class="blockquote">
    <p class="mb-0 text-justify"> It doesn't matter how beautiful your theory is, it doesn't matter how smart you are. If it doesn't agree with experiment, it's wrong</p>
    <footer class="blockquote-footer">Richard P. Feynman</footer>
  </blockquote>
</div>

  <div class="container">
    <p>
      I teach statistics and programming with R and Python to undergraduate and postgraduate students. My main courses focus on linear model, generalized linear model and time series analysis.
    </p>
    <p> Some examples are provided below:</p>
    <br>

    <ul class="list-unstyled">
      <li class="media">
        <img src="../static/stat/ts.jpg" class="mr-3" alt="..." style="width:125px;height:125px;">
        <div class="media-body">
          <h5 class="mt-0 mb-1"><a href="https://github.com/xbouteiller/TimeSeries">Time series analysis</a></h5>
          <br>
<p>This course focus on statistical mpdels useful for analysing time series from AR to SARIMA models.</p>


        </div>
      </li>
      <li class="media my-4">
        <img src="../static/stat/anova.jpg" class="mr-3" alt="..." style="width:125px;height:125px;">
        <div class="media-body">
          <h5 class="mt-0 mb-1"><a href="https://github.com/xbouteiller/CoursDA">Linear model</a></h5>
          <br>
          <p>2 Html files developped with Rmarkdown in order to teach linear regression and anova.</p>


      </li>

    </ul>

  </div>




{% endblock %}

persowebpage/templates/vitae.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron jumbotron-fluid" align='center'>
  <h1> Vitae </h1>
  <br>
  <h4> Statistics, Evolutionary Ecology and Data Science</h4>
</div>


<div class="Container">

  <div class="">
    <h2 > Present </h2>
    <br>
    <ul class="list-group">
      <li class="list-group-item border-0">Researcher in Evolutionary Ecology, Post Doctoral fellow, Biogeco, Bordeaux University</li>
      <li class="list-group-item border-0">Freelance, Expertise in Statistics and data analysis, Teaching statistics and programming</li
    </ul>
  </div>
  <br>

  <div class="">
    <h2> Positions </h2>
    <br>
    <ul class="list-group">
      <li class="list-group-item border-0">Lecturer, Data University, 2018-2020</li>
      <li class="list-group-item border-0">Data Scientist & Statistician, MP Data, 2018-2020</li>
      <li class="list-group-item border-0">Assistant Lecturer, Bordeaux University, 2018</li>
      <li class="list-group-item border-0">Physics and Chemistry teacher, French National Ministry of Education, 2008-2014</li>
    </ul>
  </div>
  <br>

  <div class="">
    <h2> Education </h2>
    <br>
    <ul class="list-group">
      <li class="list-group-item border-0">PhD in Evolutionary Ecology and Invasive Species, Bordeaux University</li>
      <li class="list-group-item border-0">Msc in Ecology, Rouen University</li>
      <li class="list-group-item border-0">Msc in Ecology, Rouen University</li>
      <li class="list-group-item border-0">Msc in fundamental Physics, Rouen University</li>
    </ul>
    <br>

  </div>

</div>




{% endblock %}